### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by raz-mon**
Prometheus data withdrawal module.

### CODE REVIEW

**Comment by sirandreww** [comment]
I don't understand why this file is needed. Right now, when I run main.py it asks me for a token, then triest to fetch each hour in the past 10 days, if an hour exists locally it skips fetching that hour. It does exactly what I would expect from a data fetching script, what feature does this PR want to add?

**Comment by raz-mon** [comment]
I'm confused. YOU suggested we upload the scripts here! I have no special desire for the code to be here.
Closing the PR.

**Comment by sirandreww** [comment]
I'm sorry if I offended you, that was not my intention.
You're right I did suggest that, but then I ended up building a script that fetches the data.
That is why I was confused.

**Comment by raz-mon** [comment]
Non taken.

**Pull request closed without merging**
